// <auto-generated />
namespace Zebra.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_product_price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_product_price));
        
        string IMigrationMetadata.Id
        {
            get { return "201710072205080_add_product_price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
